services:
  backend:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - "../.env"
    volumes:
      - "..:/app"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - shared-vpn-network

  postgres:
    image: postgres:16-alpine
    container_name: psgr
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - under-vpn-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shared-vpn-network

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    links:
      - postgres:db
    depends_on:
      - postgres
    networks:
      - shared-vpn-network

volumes:
  under-vpn-data:

networks:
  shared-vpn-network:
    driver: bridge
    name: shared-vpn-network
